# Generated by Django 4.0.6 on 2022-07-13 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noti_title', models.CharField(max_length=50)),
                ('noti_contents', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_pwd', models.CharField(max_length=30)),
                ('user_created', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Reserved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_date', models.CharField(max_length=12)),
                ('reserved_start', models.IntegerField()),
                ('reserved_end', models.IntegerField()),
                ('reserved_person', models.IntegerField(default=1)),
                ('reserved_price', models.IntegerField(default=20000)),
                ('reserved_status', models.CharField(default='wait', max_length=10)),
                ('reserved_unknown', models.BooleanField(default=False)),
                ('reserved_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goldRabbitSite.user')),
            ],
        ),
    ]
