# Generated by Django 4.0.6 on 2022-07-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldRabbitSite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserved',
            name='reserved_unknown',
            field=models.BooleanField(default=False),
        ),
    ]
