# Generated by Django 4.0.6 on 2022-07-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldRabbitSite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='noti_date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
