# Generated by Django 4.0.6 on 2022-07-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldRabbitSite', '0002_notification_noti_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='noti_date',
            field=models.CharField(max_length=20),
        ),
    ]
